language: php

services:
  - cassandra
  - couchdb
  - mongodb
  - redis-server

matrix:
    include:
        -
            dist: precise
            php: 5.5

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then sh ./tests/travis.sh; fi
  - composer self-update

install:
  - composer --prefer-source install

script:
  - vendor/bin/phpunit --verbose
